- name: Configure web servers
  hosts: all
  become: true

  tasks:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true

    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: create directory structure for web documents
      ansible.builtin.file:
        path: /web/html
        state: directory

    - name: copy nginx conf file to server
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: create link to nginx config file to enable it
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
        force: true

    - name: Generate index.html file from template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /web/html/index.html

    - name: reload nginx service
      ansible.builtin.service:
        name: nginx
        state: reloaded
        enabled: true
